artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_ULR: https://github.com/Subash7Lingden/repository-cat-vs-dog/raw/main/redwinequality.zip
  local_data_file: artifacts/data_ingestion/redwinequality.zip
  unzip_dir: artifacts/data_ingestion



data_transformation:
 root_dir: artifacts/data_transformation
 data_path: artifacts/data_ingestion/winequality-red.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib