artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_ULR: https://github.com/Subash7Lingden/repository-cat-vs-dog/raw/main/redwinequality.zip
  local_data_file: artifacts/data_ingestion/redwinequality.zip
  unzip_dir: artifacts/data_ingestion